### ISSUE TITLE
将图片路径分离（指定图片路径）

### ISSUE THREAD

**Issue by Z-fly** [Meodinger/LabelPlusFX#1]
我正使用git来驱动汉化，此为背景。
我的需求是，漫画图片能从非同一目录下读取。
我是要单独管理整个翻译工程。
而图源则是分开管理。
如果能指定路径，可以是相对路径。

**Comment by Meodinger** [comment]
我个人目前有一种对策，引入新的Json格式，把Map<PicName, Labels>改成Map<PicName, Map<FileName, Labels>>，如果在新建项目过程中导入图片时指定非同一目录读取图源就使用。这种格式的文件并不直接参与翻校嵌之间的传递，而是必须通过导出为传统项目结构（所有图源和翻译在同一目录）的压缩包的形式传递。这样的话并不会修改原本的逻辑。觉得看怎么样，或者有更好的想法的话请不吝赐教。

**Comment by Meodinger** [comment]
11月不准备大更新LPFX，12月开发2.2的时候加入这个功能

**Comment by Z-fly** [comment]
我当初的想法是默认先读取同一目录，然后在未找到图片时，弹出文件对话框选择图片所在文件夹。 这样不引入新格式的话，每次都要选图片路径。
同时导出那块得重构了。

**Comment by Meodinger** [comment]
开了新Branch来开发这个功能

**Comment by Meodinger** [comment]
更改了解决策略，引入新的成员State::projectFolder、TransFile::fileMap来解决问题，更具普适性

**Comment by Meodinger** [comment]
2.2已经发布
