### ISSUE TITLE
增加隐藏程式的快捷键

### ISSUE THREAD

**Issue by chungchungdev** [Meodinger/LabelPlusFX#11]
Labelplus原版其中一个功能
虽然有Windows+D直接显示桌面,但难免有点不自然
建议crtl /alt + D / QWRF等容易单手按的键

**Comment by Meodinger** [comment]
下个版本加上，狂按ESC就可以了

**Comment by Meodinger** [comment]
发布的2.3.1已经实现该功能，连续按Esc就可以了
