### ISSUE TITLE
这是彩蛋吗？

### ISSUE THREAD

**Issue by Z-fly** [Meodinger/LabelPlusFX#3]
https://user-images.githubusercontent.com/10470892/141686394-b0c95e06-4970-46eb-8059-9435b2e2edc0.mov

关掉软件后还有声音，把我吓了一跳，，，（你成功让我心跳停止一秒钟）
然后我立刻去下了杀毒软件。

**Comment by Z-fly** [comment]
这是怎么触发的，话说为什么要致敬DDLC，好歹是工具软件别弄得太吓人了。。。

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/141686938-d8cf5c02-de50-4d99-a3c6-ebe340ce2c03.png)

**Comment by Meodinger** [comment]
那我把触发机制写的更隐蔽一点（

**Comment by Meodinger** [comment]
> 这是怎么触发的，话说为什么要致敬DDLC，好歹是工具软件别弄得太吓人了。。。

使用Crash会触发，加个计数器吧，5次主动点击Crash才处罚

**Comment by Meodinger** [comment]
>  1.mov 
> 关掉软件后还有声音，把我吓了一跳，，，（你成功让我心跳停止一秒钟） 然后我立刻去下了杀毒软件。

Doki Doki ! （吓到你真抱歉

**Comment by Z-fly** [comment]
没看懂，什么叫使用Crash？

**Comment by Z-fly** [comment]
你应该换种形式，比如背景图改成莫妮卡之类的。现在这种形式只给人感觉是纯粹在吓人，触发了还取消不了，程序关闭后还得杀进程，真的坑啊
![image](https://user-images.githubusercontent.com/10470892/141721183-1623b540-788b-4aca-b921-3aaa242a4f52.png)

**Comment by Z-fly** [comment]
我最初以为我电脑中了勒索病毒，真的是
