### ISSUE TITLE
建议换种彩蛋或增加取消的选项

### ISSUE THREAD

**Issue by Z-fly** [Meodinger/LabelPlusFX#4]
![image](https://user-images.githubusercontent.com/10470892/141741187-fa78480e-b49e-4f3f-8d19-a184c787599f.png)

**Comment by Z-fly** [comment]
昨天被这么一搞，浪费了半个多小时，导致我组汉化进度被拖延

**Comment by Z-fly** [comment]
https://www.zhihu.com/question/306858501
你可以像这个一样在UI处加彩蛋，但是别影响主功能啊

**Comment by Meodinger** [comment]
已增加二次确认选项
![image.png](https://i.loli.net/2021/11/15/ya7WrLSm8vAZMBu.png)

**Comment by Z-fly** [comment]
触发后还是没取消的办法，与其弹出二次确认，不如做个取消来得好

**Comment by Z-fly** [comment]
彩蛋不是用来整人的啊

**Comment by Z-fly** [comment]
其次，彩蛋按照习惯应该放在关于里面(1处)，或者你可以弄个单独的选项卡(2处)，为什么要放到报错反馈那？难道你的想法是我去发个错误日志还得被整一下？你这个彩蛋设计的太失败了，我个人还是建议你取消掉这个彩蛋，彩蛋可以重新设计，如果一定要弄彩蛋，至少不能是破坏性彩蛋。单纯为了致敬DDLC而这么做，大可不必。
![image](https://user-images.githubusercontent.com/10470892/141775091-c7cb6b8f-4a65-4300-ba04-d473da310c44.png)

你也没在readme里面解释Crash到底是干嘛的，send数据到哪里。

现在我每次打开都弹出这个意义不明的对话框，你不指出哪段注释被编辑 我哪知道呢？选是和选否都没有任何意义。
![image](https://user-images.githubusercontent.com/10470892/141776401-2bdef7bd-1e4e-4dc0-88fb-1d250eb453a3.png)

**Comment by Meodinger** [comment]
注释是有默认注释列表的，列表里有LPFX，LP，萌翻的默认注释，如果注释被编辑了说明翻译可能有事情要提醒校对或者其他翻译。2.1.1已经设置这个信息只会显示一次。另外Crash是调试功能，Logs是用来上传日志的。

**Comment by Meodinger** [comment]
已于2.2.3移除，2.2.3发布时会关闭该Issue
Duplicate of #3

**Comment by Z-fly** [comment]
我自己关了吧
